### ISSUE TITLE
Long checklist items on mobile don't wrap

### ISSUE THREAD

**Issue by ocdtrekkie** [zenhack/yata#4]
This is trivial, but I noticed when adding a long item, it pushes the trash icons out of view, instead of displaying the item on multiple lines. When closing and reopening the grain, I want to say my browser shrunk everything to keep those trash icons in view, but the immediate experience wasn't perfect.

**Comment by zenhack** [comment]
Hm, can't reproduce this. Browser/OS/etc?

**Comment by ocdtrekkie** [comment]
Mobile Safari on an iPhone 11. I'll do some testing again myself tomorrow.

**Comment by ocdtrekkie** [comment]
Okay, so I figured out what happens here better. I do get wrapping if it's a bit longer than this. But here's the issue: When I click on the textbox to add an item, the iPhone decides it's too small, and *zooms in*. This also means if I have long item descriptions, the trash icons get pushed off the side.

This has the secondary oddity that now I also can't find the X to close the grain in the Sandstorm menu, because it's *also* been zoomed in.

**Comment by zenhack** [comment]
Looks like it goes off the font size:

https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone

...So probably if we increase it, that will fix the problem.

Quoting Jacob Weisz (2020-07-13 11:15:48)

**Comment by ocdtrekkie** [comment]
Intriguing. Sounds like it only cares about the input field, so we don't need to increase the font size to anything else to fix this. (Personally, the font size of the actual items is good, so I don't see a good reason to increase the size for those.)

**Comment by zenhack** [comment]
I bumped the font size for the input box (only) and pushed it to the app market (the relevant changes are also on master now). Let me know if that fixes it.

**Comment by ocdtrekkie** [comment]
Fixed by 7a8815c
